### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by gujunwuxichina** [lanyulei/ferry_web#54]
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/adobe-webplatform/eve.git E:\program\nodejs\node_cache\_cacache\tmp\git-clone-23dcce25\.git --config core.longpaths=true
npm ERR! warning: templates not found in C:\Users\user\AppData\Local\Temp\pacote-git-template-tmp\git-clone-deeea630
npm ERR! fatal: read error: Invalid argument

**Comment by lanyulei** [comment]
推荐使用cnpm。
